machine:
  ruby:
    version:
      2.5.3
test:
  override:
    - bundle exec jekyll build

jobs:
  build-job:
    steps:
     - checkout
     - run: bundle install
     - run: bundle exec jekyll build
     - run: echo "Build finished!"
